// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/discussions": {
            "get": {
                "description": "Retrieves a list of all discussions with their summaries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "List all discussions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-api_ListDiscussionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new discussion with the specified title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Create a new discussion",
                "parameters": [
                    {
                        "description": "Discussion creation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateDiscussionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-discussion_CreateDiscussionResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discussions/{id}": {
            "get": {
                "description": "Retrieves a complete discussion including all messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Get a discussion by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-discussion_DiscussionDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discussions/{id}/history": {
            "get": {
                "description": "Retrieves all messages in a discussion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Get discussion message history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-discussion_GetDiscussionHistoryResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discussions/{id}/question": {
            "post": {
                "description": "Adds a user question to a discussion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Ask a question in a discussion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AskQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-discussion_AskQuestionResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discussions/{id}/question/stream": {
            "post": {
                "description": "Adds a user question to a discussion and streams the AI response using Server-Sent Events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Ask a question with streaming response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AskQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streaming response",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-api_HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/index-github": {
            "post": {
                "description": "Fetches and indexes the contents of a GitHub repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexing"
                ],
                "summary": "Index a GitHub repository",
                "parameters": [
                    {
                        "description": "Repository indexing parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IndexGithubRepoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-api_IndexGithubRepoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions": {
            "post": {
                "description": "Asks a question, creating a new discussion if discussion_id is not provided. Uses mistral:latest to auto-generate discussion titles.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Ask a question (with auto-discussion creation)",
                "parameters": [
                    {
                        "description": "Question parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.QuickQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse-discussion_AskQuestionQuickResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions/stream": {
            "post": {
                "description": "Asks a question with streaming response, creating a new discussion if discussion_id is not provided",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Ask a question with streaming (with auto-discussion creation)",
                "parameters": [
                    {
                        "description": "Question parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.QuickQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streaming response",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AskQuestionRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "example": "What are vector embeddings?"
                }
            }
        },
        "api.CreateDiscussionRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "example": "How to use embeddings?"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request parameters"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "api.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "local-rag-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.IndexGithubRepoRequest": {
            "type": "object",
            "required": [
                "github_url"
            ],
            "properties": {
                "file_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "md",
                        "mdx"
                    ]
                },
                "github_url": {
                    "type": "string",
                    "example": "https://github.com/username/repo"
                },
                "target_index": {
                    "type": "string",
                    "example": "target_index"
                }
            }
        },
        "api.IndexGithubRepoResponse": {
            "type": "object",
            "properties": {
                "index_id": {
                    "type": "string",
                    "example": "target_index"
                }
            }
        },
        "api.ListDiscussionsResponse": {
            "type": "object",
            "properties": {
                "discussions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discussion.DiscussionSummaryDTO"
                    }
                }
            }
        },
        "api.QuickQuestionRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "discussion_id": {
                    "type": "string",
                    "example": ""
                },
                "question": {
                    "type": "string",
                    "example": "What are vector embeddings?"
                }
            }
        },
        "api.SuccessResponse-api_HealthCheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.HealthCheckResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-api_IndexGithubRepoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.IndexGithubRepoResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-api_ListDiscussionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.ListDiscussionsResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-discussion_AskQuestionQuickResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/discussion.AskQuestionQuickResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-discussion_AskQuestionResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/discussion.AskQuestionResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-discussion_CreateDiscussionResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/discussion.CreateDiscussionResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-discussion_DiscussionDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/discussion.DiscussionDTO"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SuccessResponse-discussion_GetDiscussionHistoryResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/discussion.GetDiscussionHistoryResult"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "discussion.AskQuestionQuickResult": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_timestamp": {
                    "type": "string"
                },
                "assistant_message_id": {
                    "type": "string"
                },
                "discussion_id": {
                    "type": "string"
                },
                "discussion_title": {
                    "type": "string"
                },
                "is_new_discussion": {
                    "type": "boolean"
                },
                "question": {
                    "type": "string"
                },
                "question_timestamp": {
                    "type": "string"
                },
                "user_message_id": {
                    "type": "string"
                }
            }
        },
        "discussion.AskQuestionResult": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_timestamp": {
                    "type": "string"
                },
                "assistant_message_id": {
                    "type": "string"
                },
                "discussion_id": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "question_timestamp": {
                    "type": "string"
                },
                "user_message_id": {
                    "type": "string"
                }
            }
        },
        "discussion.CreateDiscussionResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "discussion.DiscussionDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discussion.MessageDTO"
                    }
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "discussion.DiscussionSummaryDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "discussion.GetDiscussionHistoryResult": {
            "type": "object",
            "properties": {
                "discussion_id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discussion.MessageDTO"
                    }
                }
            }
        },
        "discussion.MessageDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Local RAG API",
	Description:      "API for local RAG indexing and document management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
